#%RAML 1.0 SecurityScheme
type: x-client-credentials
describedBy:
  headers:
    client_id:
      type: string
      required: true
      example: 09bd0e18-baae-45c0-b2ce
      description: Client Id provided by API Manager
    client_secret:
      type: string
      required: true
      example: 16253d08-f112-4e7f-ad4c
      description: Client Secret provided by API Manager
